const reyes = [
  {
    nombre: 'Atanagildo',
    color: 'darkolivegreen',
    precio: 178,
    url: 'https://www.html6.es/img/rey_atanagildo.png',
    reinado: 15,
    vacasComidas: 9,
  },
  {
    nombre: 'Ervigio',
    color: 'crimson',
    precio: 169,
    url: 'https://www.html6.es/img/rey_ervigio.png',
    reinado: 7,
    vacasComidas: 3,
  },
  {
    nombre: 'Ataúlfo',
    color: 'peru',
    precio: 81,
    url: 'https://www.html6.es/img/rey_ataulfo.png',
    reinado: 5,
    vacasComidas: 16,
  },
  {
    nombre: 'Leogivildo',
    color: 'darkmagenta',
    precio: 126,
    url: 'https://www.html6.es/img/rey_leogivildo.png',
    reinado: 18,
    vacasComidas: 3,
  },
  {
    nombre: 'Recesvinto',
    color: 'royalblue',
    precio: 141,
    url: 'https://www.html6.es/img/rey_recesvinto.png',
    reinado: 19,
    vacasComidas: 11,
  },
  {
    nombre: 'Sisebuto',
    color: 'teal',
    precio: 69,
    url: 'https://www.html6.es/img/rey_sisebuto.png',
    reinado: 9,
    vacasComidas: 13,
  },
  {
    nombre: 'Teodorico',
    color: 'black',
    precio: 243,
    url: 'https://www.html6.es/img/rey_teodorico.png',
    reinado: 33,
    vacasComidas: 12,
  },
]

export default reyes
